package satrapia.clases.geografia

//import satrapia.clases.geografia.Coord
//import satrapia.clases.geografia.TipoTerrenos

class Punto {
    Punto(let coordenadas: Coord, let terreno: TipoTerrenos) {}
}

/* main() {
    let c: Coord = Coord(10,15)
    let t: TipoTerrenos = Desierto()
    let p: Punto = Punto(c, t)

    print("pos: [${p.coordenadas.x}, ${p.coordenadas.y}] terreno: ${p.terreno.nombre}")
} */