[package]
  cjc-version = "1.0.0"
  name = "satrapia"
  description = "a satrapia implementation in Cangjie"
  version = "1.0.0"
  target-dir = ""
  src-dir = ""
  output-type = "executable"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
